permissionset 72000 "All"
{
    Assignable = true;
    Caption = 'SKU Load Integration customization permissions', Locked = true;

    Permissions =
         codeunit "SKU Delivery Buffer Mgt" = X,
         codeunit "SKU Invoice Buffer Mgt" = X,
         codeunit "SKU Invoice Events" = X,
         codeunit "SKU Order Conf Buffer Mgt" = X,
         codeunit "SKU Order Conf Push" = X,
         //codeunit "SKU Order Conf Sales Events" = X,
         codeunit "SKU 850 Order Buffer Mgt" = X,
         codeunit SKUAppTexts = X,
         codeunit SKUShipmentFieldCopyMgmt = X,
         page "SKU Deliveries API" = X,
         page "SKU Delivery Lines API" = X,
         page "SKU Invoice Lines API" = X,
         page "SKU Invoices API" = X,
         page "SKU Order Conf Lines API" = X,
         page "SKU Order Confirmations API" = X,
         page "EDI SSales Order Header API" = X,
         page "EDI SSales Order Line API" = X,
         page "SKU Product Prices API" = X,
         page SKUIntegrationLog = X,
         page SKUIntegrationSetup = X,
         table "SKU Delivery Buffer" = X,
         table "SKU Delivery Line Buffer" = X,
         table "SKU Invoice Buffer" = X,
         table "SKU Invoice Line Buffer" = X,
         table "SKU Order Conf Buffer" = X,
         table "SKU Order Conf Line Buffer" = X,
         table "SKU 850 Order Buffer" = X,
         table "SKU 850 Order Line Buffer" = X,
         table "SKU Product Price Buffer" = X,
         table SKUIntegrationLog = X,
         table SKUIntegrationSetup = X,
         tabledata "SKU Delivery Buffer" = RIMD,
         tabledata "SKU Delivery Line Buffer" = RIMD,
         tabledata "SKU Invoice Buffer" = RIMD,
         tabledata "SKU Invoice Line Buffer" = RIMD,
         tabledata "SKU Order Conf Buffer" = RIMD,
         tabledata "SKU Order Conf Line Buffer" = RIMD,
         tabledata "SKU 850 Order Buffer" = RIMD,
         tabledata "SKU 850 Order Line Buffer" = RIMD,
         tabledata "IWX LP Line Usage" = R,
         tabledata "SKU Product Price Buffer" = RIMD,
         tabledata SKUIntegrationLog = RIMD,
         tabledata SKUIntegrationSetup = RIMD;
}